### ISSUE TITLE
Redefinition of module ReactCommon when upgrading to 0.74

### ISSUE THREAD

**Issue by justbaum30** [reactwg/react-native-releases#284]
### Old Version

0.73.8

### New Version

0.74.1

### Description

After upgrading to 0.74.1, I am no longer able to build the application on iOS. I receive build errors indicating that the `ReactCommon` module is redefined. Usually it's with `React-AppleRuntime` but I have also seen it with `RCTAppDelegate`.

I am able to reproduce by simply adding the same dependencies and Podfile as I have in the reproducer repository. 

### Steps to reproduce

1. Install the application with `npm install`
2. Install the iOS dependencies with `pod install`
3. Try to run the application with `npm run start`

### Affected Platforms

Runtime - iOS, Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 49.57 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman:
    version: 2023.11.06.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 34.0.0
      - 35.0.0
    System Images:
      - android-30 | Google APIs Intel x86 Atom
      - android-31 | Google APIs Intel x86_64 Atom
      - android-34 | Google APIs Intel x86_64 Atom
      - android-34 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.6
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
/Users/justinbaumgartner/Development/NVA/hhp-mobile/nvaMobileGP/ios/Pods/Headers/Public/ReactCommon/ReactCommon.modulemap:1:8: error: redefinition of module 'ReactCommon'
module ReactCommon {
       ^
/Users/justinbaumgartner/Development/NVA/hhp-mobile/nvaMobileGP/ios/Pods/Headers/Public/ReactCommon/React-RuntimeApple.modulemap:1:8: note: previously defined here
module ReactCommon {
       ^
1 error generated.

....

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/justinbaumgartner/Library/Developer/Xcode/DerivedData/nvaMobileGP-biigwvvmhyomegaepvdbpuhuakly/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-RCTAppDelegate.build/Objects-normal/x86_64/React-RCTAppDelegate-dummy.o /Users/justinbaumgartner/Development/NVA/hhp-mobile/nvaMobileGP/ios/Pods/Target\ Support\ Files/React-RCTAppDelegate/React-RCTAppDelegate-dummy.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-RCTAppDelegate' from project 'Pods')
(1 failure)
]
```

### Reproducer

https://github.com/justbaum30/rn-74-upgrade-reproducer

### Screenshots and Videos

![Screenshot 2024-05-07 at 4 34 31 PM](https://github.com/reactwg/react-native-releases/assets/1571999/1bbce2cf-dee3-4dbe-bcde-1bc4af9cc72f)

**Comment by MarceloCajueiro** [comment]
Same thing happening here.

**Comment by anuragipankaj** [comment]
same thing with me

**Comment by cipolleschi** [comment]
Hi there! Sorry for the long delay, but with the React Conf coming up I hadn't time to look into this.
I'm cloning the reproducer now to see what's going on! Thanks @justbaum30 for providing it!

**Comment by cipolleschi** [comment]
Hi There, I had a look at this issue. It looks like you are using [Firebase](https://github.com/justbaum30/rn-74-upgrade-reproducer/blob/main/ReproducerApp/package.json#L20-L23) in the app.

When using Firebase, you have to follow the [Firebase setup steps](https://rnfirebase.io/#altering-cocoapods-to-use-frameworks).

Once that's done, you'll find another problem in `RNCheckNotificationPermission` library. [This import](https://github.com/duongxuannam/react-native-check-notification-permission/blob/master/ios/RNCheckNotificationPermission.mm#L8) is broken, there is no `rNCheckNotificationPermission` file in the library. That line should be replaced by the following.

```diff
- #import "rNCheckNotificationPermission-Swift.h"
+ #import "RNCheckNotificationPermission/RNCheckNotificationPermission-Swift.h"
```

with these two changes, the build will fail because the `GOOGLE_APP_ID` setting is missing. [This](https://stackoverflow.com/questions/56942806/react-native-build-error-could-not-get-google-app-id-in-google-services-file-fr) should help.

**Comment by elgambet** [comment]
I'm using Crashlytics and experiencing the same issue with Xcode Version 15.4. Initially, I was using version 0.72.5, and iOS builds were successful. However, after upgrading to version 0.74.2, this error began to occur. I tried installing version 0.73.8, and it does work there.

In my project, the pods are being added like this:

```ruby
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
```

I tried changing the configuration to:

```ruby
use_frameworks! :linkage => :static
```
but this generated other sorts of errors.

I have attempted to clean the build folder and erase the derived data, but these steps did not resolve the issue with version 0.74.2. For now, I will use version 0.73.8 until a fix for this error can be found.

Additionally, I am not using RNFirebase.

Any assistance would be greatly appreciated.

**Comment by eunbae0** [comment]
Hi. I fixed this issue through the process of adding and deleting from the code below.

```ruby
$RNFirebaseAsStaticFramework = false // delete
$RNFirebaseAnalyticsWithoutAdIdSupport = true // delete

use_modular_headers! // delete

target 'YOUR_TARGET' do
  config = use_native_modules!

  use_frameworks! :linkage => :static # add
  $RNFirebaseAsStaticFramework = true # add

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    )
end
```

Additionally, I use RNFirebase and upgrade react-native version from `0.71.19` to `0.74.1`

**Comment by sireeshp** [comment]
@eunbae0  can you please paste POD file, AppDelegate.mm, After I added Firebase it's failed tried your above suggestion but still the same issue.

**Comment by eunbae0** [comment]
@sireeshp This is my entire Podfile & AppDelegate.mm 
```ruby
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'YOUR_TARGET' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    )
end

post_install do |installer|
  react_native_post_install(
    installer,
    :mac_catalyst_enabled => false,
  )
  installer.pods_project.targets.each do |target|
    if target.name == "React-Core.common-AccessibilityResources"
      target.remove_from_project
    end
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```
```c
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <CodePush/CodePush.h>
#import <Firebase.h>
#import "RNBootSplash.h"
#import "SDImageCodersManager.h"
#import <SDWebImageWebPCoder/SDImageWebPCoder.h>
#import <React/RCTLinkingManager.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"uoslife";
  self.initialProps = @{};

  [FIRApp configure];

  bool didFinish = [super application:application didFinishLaunchingWithOptions:launchOptions];

  [SDImageCodersManager.sharedManager addCoder:SDImageWebPCoder.sharedCoder];

  return didFinish;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  return [self bundleURL];
}
 
- (NSURL *)bundleURL
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [CodePush bundleURL];
#endif
}

- (void)customizeRootView:(RCTRootView *)rootView {
  [RNBootSplash initWithStoryboard:@"BootSplash" rootView:rootView]; // ⬅️ initialize the splash screen
}

- (BOOL)concurrentRootEnabled
{
  return true;
}

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

@end

```

I hope this will help you. And [react-native-upgrade-helper](https://react-native-community.github.io/upgrade-helper/) might help you.

**Comment by balramsinghindia** [comment]
I had the same issue with other pods (Firebase). I assume the issue has to do with recursive dependecnies that are also imported explicitly. I tried all the same things as you did, although the only thing that helped me was to close xcode, run

```
pod deintegrate
pod install
```
and rebuild.

**Comment by ashwini-ksingh** [comment]
@cipolleschi Thanks, using frameworks as suggested by firebase solved the issue.

**Comment by seanquinn** [comment]
To add to @eunbae0 answer, you may need to the pods for Firebase and GoogleUtilities to function

```swift

target 'app' do
  config = use_native_modules!

  pod 'FirebaseCore', :modular_headers => true;
  pod 'GoogleUtilities', :modular_headers => true;

  if linkage != nil
    Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
    use_frameworks! :linkage => :static
    $RNFirebaseAsStaticFramework = true
  end

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

```

**Comment by saadiyakazi** [comment]
Hi
```

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

  
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
# require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '15'
prepare_react_native_project!
require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

linkage = ENV['USE_FRAMEWORKS']
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
   use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

target 'OptimizeApp' do


  use_expo_modules!
  pod 'sovran-react-native', :path => '../node_modules/@segment/sovran-react-native'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'


  pod 'Firebase', :modular_headers => true
  pod 'FirebaseAppCheck', :modular_headers => true

  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  pod 'react-native-ffmpeg/https-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'

  # rn_maps_path = '../node_modules/react-native-maps'
  # pod 'react-native-google-maps', :path => rn_maps_path
  # pod 'GoogleMaps'
  # pod 'Google-Maps-iOS-Utils'

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-ffmpeg/https-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'


  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  # pod 'RNAnalyticsIntegration-Mixpanel', :path => '../node_modules/@segment/analytics-react-native-mixpanel'

  pod 'RNVideoEditorSDK', :path => '../node_modules/react-native-videoeditorsdk'

  
  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  pod 'RNPhotoEditorSDK', :path => '../node_modules/react-native-photoeditorsdk'

  # pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNBootSplash', :path => '../node_modules/react-native-bootsplash'


  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'react-native-idfa',  path: '../node_modules/react-native-idfa'


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNCClipboard', :path => '../node_modules/@react-native-clipboard/clipboard'

  pod 'react-native-fbsdk-next', :path => '../node_modules/react-native-fbsdk-next'
  
  pod 'customerio-reactnative/apn', :path => '../node_modules/customerio-reactnative'

  pod 'react-native-biometrics', :path => '../node_modules/react-native-biometrics', :modular_headers => true
  cio_target_names = [
      'Gist',
      'CustomerIOTracking',
      'CustomerIOCommon',
      'CustomerIOMessagingPushAPN',
      'CustomerIOMessagingPush'
    ]
 
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
     system("chmod -R u+w Pods/RCT-Folly")
      Dir.glob("Pods/RCT-Folly/folly/Portability.h").each do |file|
        text = File.read(file)
        new_contents = text.gsub('#define FOLLY_HAS_COROUTINES 1', '#define FOLLY_HAS_COROUTINES 0')
        File.open(file, "w") { |file| file.puts new_contents }
      end
    end
    

    bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
   def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
     framework_path = File.join(Dir.pwd, framework_relative_path)
     command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
     puts "Stripping bitcode: #{command}"
     system(command)
   end

   framework_paths = [
     "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/hermes",
     "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/Versions/Current/hermes",
     "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes",
     "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/hermes"
   ]

   framework_paths.each do |framework_relative_path|
     strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
   end
     # fix xcode 15 DT_TOOLCHAIN_DIR - remove after fix oficially - https://github.com/CocoaPods/CocoaPods/issues/12065
    installer.aggregate_targets.each do |target|
        target.xcconfigs.each do |variant, xcconfig|
        xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
        end
      end
  
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
            xcconfig_path = config.base_configuration_reference.real_path
            IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
        end
      end
    end  
    react_native_post_install(installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
      )

    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
  # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          config.build_settings['EXCLUDED_ARCHS'] = 'i386'
        end
      end
      aggregate_target.user_project.save
    end

    # Workaround `Cycle inside FBReactNativeSpec` error for react-native 0.64
    # Reference: https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # unless ['React-Core', 'React-RCTText'].include? target.name
        #   config.build_settings["USE_HEADERMAP"] = "NO"
        # end
        target.build_configurations.each do |config|
          config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        end
      end
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
      if cio_target_names.include? target.name 
        puts "Modifying target #{target.name}"
    
        target.build_configurations.each do |config|
          puts "Setting build config settings for #{target.name}"
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] ||= 'NO'
        end
      end
    end
  end

end

target 'OptimizeAppServiceExtension' do
  # Notice the '-richpush' in the line below. This line of code is different from what you added for your main target. 
  pod 'customerio-reactnative-richpush/apn', :path => '../node_modules/customerio-reactnative'
end

```
![Screenshot 2024-12-05 at 14 53 25](https://github.com/user-attachments/assets/639c3acb-7363-4bee-b9d1-2ac29f5a81cc)


getting the following.  error on xcode15

```
react-native: 0.74.5
expo: 51.0.28

```

**Comment by Falpangaea** [comment]
@eunbae0 I spent the last two days attempting to follow the multiple versions of the official instructions and your code is what actually made it work.  Thank. You.  I was tearing my hair out.
